name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build geosite
        id: build
        run: |
          go run -v .

      - name: Generate sha256 hash
        if: steps.build.outputs.skip != 'true'
        run: |
          sha256sum geosite.db > geosite.db.sha256sum

      - uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a release
        if: steps.build.outputs.skip != 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build.outputs.tagName }}
          release_name: ${{ steps.build.outputs.tagName }}
          draft: false
          prerelease: false

      - name: Release geosite.db
        if: steps.build.outputs.skip != 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./geosite.db
          asset_name: geosite.db
          asset_content_type: application/octet-stream

      - name: Release geosite.db sha256sum
        if: steps.build.outputs.skip != 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./geosite.db.sha256sum
          asset_name: geosite.db.sha256sum
          asset_content_type: text/plain

      - name: Git push assets to "release" branch
        run: |
          install -Dp ./geosite.db ./publish/geosite.db
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "17228526+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ steps.build.outputs.tagName }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      - name: CDN
        run: |
          cd publish || exit 1
          for file in $(ls); do
            curl -i "https://cdn.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done
